### ISSUE TITLE
テキスト印刷での改行機能が動作しない問題

### ISSUE THREAD

**Issue by Umem0d0ki** [mitsuharu/mobile-printer#357]
現在、このアプリで入力フォームを使用している際、改行が正しく機能しない問題に直面しています。テキストエディターで内容を決めれるようにしたいです。

この問題を解決するために、テキストの決定をつかさどるコードや関連する部分のソースコードの場所を教えていただけますか？また、改行機能が意図した通りに動作するようにするための修正方法についてもアドバイスをいただけると助かります。

ご確認のほどよろしくお願いいたします。

**Comment by mitsuharu** [comment]
テキスト印刷は改行自体はサポートしています。入力フォームが改行入力を想定していないだけで、他エディターからコピー＆ペーストをすれば、改行ありでも印刷できます。したがって、テキスト入力周りのフォームを修正すればOKです。PRをお待ちしております。

|入力|印刷|
| --- | --- |
|  ![IMG_0412](https://github.com/user-attachments/assets/cee4b825-e959-4ea5-8968-f566fe766532) |  ![IMG_0413](https://github.com/user-attachments/assets/f16861f8-9300-4dc6-927a-623ce2703d2c) |
